doy/rbw

- src/cipherstring.rs
Fixes #5.
Cipherstring type `6` is `Rsa2048_OaepSha1_HmacSha256_B64`.
`rbw` currently supports `Rsa2048_OaepSha1_B64` but not the deprecated option above.
The `HMAC` `SHA256` deprecated versions append a `|` and the signature to the ciphertext. This fix simply ignores the appended signature, since it's a [deprecated mode anyways](https://github.com/bitwarden/jslib/blob/c62f5287cd259c6385c6e79193e0e5e1746c7a3c/src/services/crypto.service.ts#L620).
This PR does not add support for [`Rsa2048_OaepSha256_HmacSha256_B64`](https://github.com/bitwarden/jslib/blob/785b681f61f81690de6df55159ab07ae710bcfad/src/enums/encryptionType.ts#L7) since I have no way of testing it, although I'd imagine its the same.
> Add CipherString type 6 support

- src/bin/rbw/commands.rs
`oath::totp_raw_now` doesn't zero-pad the result.
For example the following code outputs `3406` instead of `003406`:
```rust
extern crate oath;
use oath::{totp_raw_custom_time, HashType};
fn main () {
let res = totp_raw_custom_time(b"12345678901234567890", 6, 0, 30, 26*365*24*60*60, &HashType::SHA1);
println!("{}", res);
}
```
> Zero-pad auth code

- src/api.rs
Only allows deserialization for the new provider. See
https://github.com/bitwarden/server/pull/903
> TwoFactorProviderType: Allow WebAuthn

- src/bin/rbw/commands.rs
Piping stdout to something like `head`, which closes rbw's stdout before
it's done writing everything, causes a panic.
The panic is circumvented by using `writeln!` instead of `println!` and
ignoring the error when it's of kind `BrokenPipe`.
Closes #79
> fix: don't panic when piping

- src/actions.rs
- src/api.rs
- src/bin/rbw/commands.rs
- src/config.rs
Added config `client_cert_path` to be used such as:
```
rbw config set client_cert_path /path/to/pem
```
File should contain certificate and private key (`cat private.key client.pem > final.path`)
While bitwarden server (or vaultwarden) do not support mTLS, self-hosting users can have cloudflare/nginx/traefik/whatever in front requiring one.
Even if not widely used, I believe it's a very small change, easy enough to support.
> support for client certificates

- src/bin/rbw-agent/actions.rs
- src/dirs.rs
This introduces the `RBW_PROFILE` environment variable to be able to run multiple instances in parallel, that will use different configuration paths.
To use this feature, simply run `rbw` with the environment variable set to any string that is valid for a path. Setting it to an empty string is like not setting it at all.
e.g.:
* `RBW_PROFILE=perso rbw list`
* `RBW_PROFILE=pro rbw list`
Fixes #48 and probably #28.
> Support multiple profiles with an environment variable

- README.md
- src/bin/rbw/commands.rs
- src/bin/rbw/main.rs
I added a basic `--field` flag that can be used to get any specific field from an item when using the `get` command. The idea is to make it easier for someone to access just the username or whatever custom field they've defined in an item without needing to use the `--full` flag and then parsing the output
> Added a field flag to the get command

- README.md
This is clearly a self-made ad for my project here. Feel free to dismiss.
I was previously using some `env SSHPASS=(rbw get "smtp-out1.example.com" "root") sshpass -e ssh root@smtp-out1.example.com` and thought that it was not optimal. I've found some projects that store the entire private key in Bitwarden, which is defeating the purpose of *private* key.
So, I created this. This is really a custom tool, made for me, as a proof-of-concept. If people like it, I'll make it more user-friendly.
> Add bw-ssh related project

- README.md
- src/bin/rbw/commands.rs
- src/bin/rbw/main.rs
This is a very basic implementation, and I wanted to get some feedback on the direction before taking it further. What do you think so far? My goal is compatibility with chezmoi's [bitwarden](https://www.chezmoi.io/reference/templates/bitwarden-functions/bitwarden/) and [bitwardenFields](https://www.chezmoi.io/reference/templates/bitwarden-functions/bitwardenFields/) functions, which uses the official cli's json output, but general usability is also good.
fixes #36
example usage:
```json
$ cargo run -q --bin rbw -- get --raw test-entry
{
"id": "adf723e1-ab03-4ff3-81aa-f5f3c2b68a5f",
"folder": null,
"name": "test-entry",
"data": {
"username": "foo",
"password": "hunter2",
"totp": null,
"uris": [
{
"uri": "example.com",
"match_type": null
}
]
},
"fields": [
{
"name": "some-text",
"value": …
```
> add support for raw json output

- src/api.rs
- src/bin/rbw-agent/actions.rs
Generalize the `two_factor` function to allow for different Providers. The `login` function now holds a list of supported providers that it tests in turn. The list should probably adhere to
https://bitwarden.com/help/setup-two-step-login/#using-multiple-methods.
Closes #90.
NB: This is the first time I write Rust code, so please review.
> Add support for 2FA-method 'Email'.

- src/identity.rs
Seems my test account was set to pbkdf2 when I tested the argon2 PR after switching to rustcrypto. The login did not actually work on argon2 after switching (sorry about that). This PR fixes the login on argon2.
> Fix argon2 login

- Cargo.lock
- Cargo.toml
- src/bin/rbw-agent/actions.rs
- src/bin/rbw-agent/agent.rs
- src/bin/rbw-agent/main.rs
- src/bin/rbw-agent/notifications.rs
This PR adds basic support for Websocket notifications. ~~It still far from ready for merging but I'm opening it as a draft PR in case anyone has comments.~~
Related issue: https://github.com/doy/rbw/issues/112
The PR currently does a full sync whenever an item changes (though the parsing part of which item changed is not too difficult, so this could be improved later). 
Furthermore, it also implements the logout message, sent when de-authorizing sessions in the web UI.
The code is structured, such that adding more message types (passwordless login request) should not be too difficult.
If the server does not support Websockets, it silently fails.
The connection is tried when starting the agent, and when a login is successful.
> Implement basic websocket support

- bin/rbw-pinentry-keyring
Hello,
I wrote a little pinentry-script to store the master password for rbw into the system keyring.
Thought I share this, since this functionality was requested before in #16.
The pinentry-code is mostly taken from #108 and I updated + extended it to support keyring using secret-tool.
Tested on Fedora 37 (with pinentry-gnome3 for setup).
> Add script to store master password in keyring

- src/api.rs
- src/bin/rbw-agent/actions.rs
This is all that's needed to support Yubikey hardware tokens in OTP mode (https://developers.yubico.com/OTP/)
Fixes: #7
> add yubikey support

- README.md
Hi! Firstly thanks for the project, it's awesome and I use it every day.
I've made an absolutely tiny bash script to wire rbw to fuzzy menus like wofi (which is the default). I'm not even sure it's complicated enough to share (it started out bigger and shrank as I figured out ways to simplify it), but I wanted to offer an alternative to rofi-rbw. That project is great, but it's like 1000 lines of python and I just wanted keybindings for copying credentials to the clipboard.
No hard feelings if you say no, I just thought it might be helpful. Thanks!
https://github.com/rbuchberger/rbw-menu
> Add rbw-menu as a related project

- src/pinentry.rs
Just now rbw-agent will spin at 200% cores if pinentry fails, which can have various reasons. Now it will just terminate correctly when this happens.
This happens often to me when I close the terminal that runs pinentry.
> handle eof correctly when reading from pinentry

- src/api.rs
> Pass `User-Agent` header to prevent login from returning 400

- src/config.rs
Bitwarden have introduced an eu instance of their service. 
This needs to be reflected in the code by excluding the eu addresses from URL formatting.
Fixes #148 
See [https://bitwarden.com/help/public-api/](https://bitwarden.com/help/public-api/) for URL information.
> Fix bitwarden.eu URLs

- src/bin/rbw-agent/daemon.rs
- src/bin/rbw-agent/main.rs
I'm running `rbw-agent` with `--no-daemonize`, and that fails because the runtime directory for the socket file does not exist yet.
Related: #87
> Make directories when not daemonized

- src/bin/rbw/commands.rs
- src/bin/rbw/main.rs
This merge request aims to address this issue: https://github.com/doy/rbw/issues/26
I'd appreciate a preliminary code-review (it's far from finished), I just want to get some feedback before I spend more time on something that is potentially flawed.
_Please, keep in mind I am completely new to Rust - I am not at all versed with Rust's idioms and other bells and whistles.
That being said, I am looking for any constructive criticism I can get._
> [WIP] add URI matching for 'rbw get'

- src/bin/rbw/commands.rs
This fixes #171.
- The code now extracts the algorithm, digits and period query parameter from the totp URL too.
- `parse_totp_secret` now returns the `TotpParams` struct
- `generate_totp` now uses the `totp_params.algorithm` to pass the correct hash type to `totp_lite::totp_custom`.
- Code duplication seems to be "necessary" as the hash type needs to be known at compile time, or at least I couldn't figure out another way.
- `generate_totp` also uses the parsed number of digits and the time period.
- There should be no behaviour changes compared to the previous version of the code for URLs without these parameters.
> add sha256 and sha512 support for totp

- src/bin/rbw/commands.rs
- src/bin/rbw/main.rs
a864366e60f6e7ae67df91010d7e30f3b1569ac0 changed the implementation of
`find_entry` to work on the new `Needle` type, but when calling into it from the
`code` subcommand the provided string was only passed as a `Needle::Name` when
in fact also UUIDs are allowed.
Remedy this by parsing the first argument in the same way as with the `get`
command, which also enables passing URIs
Signed-off-by: Robert Günzler <r@gnzler.io>
> Support UUIDs and URIs in code command

- src/api.rs
Since recently, official Bitwarden server started rejecting authentication requests to the `/connect/token` endpoint if they do not have specific HTTP headers set.
FTR, as of now, values of these headers do not seem to matter.
Fixes #173
> Add new headers required by the Bitwarden server

- src/api.rs
the official bitwarden cli uses the following parameters when logging in (POST /connect/token):
```
scope=api offline_access
client_id=cli
deviceType=25
deviceIdentifier=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
deviceName=linux
grant_type=password
username=xxxxxxxxxxxxxxxxxxxxxxxxx
password=xxxxxxxxxxxxxxxxxxxxxxxxx
```
before this commit, rbw uses these parameters:
```
scope=api offline_access
client_id=desktop
deviceType=8
deviceIdentifier=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
deviceName=rbw
devicePushToken=
grant_type=password
username=xxxxxxxxxxxxxxxxxxxxxxxxx
password=xxxxxxxxxxxxxxxxxxxxxxxxx
```
although there are multiple differences, changing the client id from "desktop" to "cli" is sufficient to fix the issue.
> fix: use "cli" as client id when logging in, fixes #182

- bin/rbw-pinentry-keyring
This PR solves 3 things:
1. 
the rbw-pinentry-keyring setup command did not support passwords that includes a space. The cut command only retrieved the first word of the password and thus skipping the other words. `cut -c3-` cuts from the 3rd char 'D ' to the end of the line. 
So pinentry output like `D this is a passphrase` will be cut to `this is a passphrase`.
Can be tested with the following commands:
old: `echo "D this is a passphrase" | cut -d' ' -f2`
new: `echo "D this is a passphrase" | cut -c3-`
2.
Also the script doesnt work with 2fa codes because the secret-tool is called for the 2fa code instead of the system pinentry. This PR also fixes that bug.
3.
This PR also removes the setup command and it will auto setup if the password is not found in the keyring. Also there is a new …
> fix rbw-pinentry-keyring not saving passwords correctly and not working with 2fa codes and add auto setup

- Cargo.lock
- Cargo.toml
- README.md
- src/actions.rs
- src/api.rs
- src/bin/rbw/commands.rs
- src/config.rs
- src/error.rs
Resolves https://github.com/doy/rbw/issues/118
Implementation is mostly ported from the [official CLI](https://github.com/bitwarden/clients/blob/main/apps/cli/src/auth/commands/login.command.ts#L109), with minor changes to utilise having predefined `sso_id` in the config file.
Tested with Google based SSO.
Can be summarised with:
1. Generate two random values, `state` and `ssoCodeVerifier`
2. hash and B64 escape the `ssoCodeVerifier`
3. spin up a local callback server (I assume port range is important here because of the allowed `redirect_uris` on Bitwarden end)
4. open a webbrowser initializing the SSO flow using the previously generated values
5. obtain the `authorization_code` via the callback server
6. replace the code for tokens by calling the `/identity/token` endpoint (same as for …
> Add support for SSO login

- src/bin/rbw/commands.rs
- src/bin/rbw/main.rs
Hi @doy,
I have implemented a CLI option for case-insensitive name search (#144), as this is the one feature I miss from `rbw`.
I would be happy to adapt the PR with your suggestions.
> Add CLI option for case-insensitive search.

- src/bin/rbw/commands.rs
After a recent update, most of my TOTP secrets stopped working, with the message:
```
rbw code: totp secret was not valid base32
```
I found that it's because they must be uppercase now. 
This patch makes the secret uppercase, before decoding, which resolves the issue for me.
> fix `rbw code: totp secret was not valid base32`

- Cargo.toml
`rbw` uzes `LazyLock` which is only stabilized in 1.80.0
e.g. when building on RHEL 9 or derivatives (which currently has 1.79.0 - it will be refreshed in the next RHEL minor release)
https://koji.fedoraproject.org/koji/taskinfo?taskID=129121049
```
error[E0658]: use of unstable library feature 'lazy_cell'
--> src/protocol.rs:70:5
|
70 | > = std::sync::LazyLock::new(|| {
|     ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
= help: add `#![feature(lazy_cell)]` to the crate attributes to enable
= note: this compiler was built on 2024-06-10; consider upgrading it if it is out of date
```
see https://doc.rust-lang.org/std/sync/struct.LazyLock.html for the version it's stabilized
> Add rust-version metadata to declare MSRV

- src/bin/rbw/commands.rs
This fixes a regression from 391c8d5, which fixes #56.
> remove spaces from totp secrets

- bin/git-credential-rbw
This allows users who use git's `credential.useHttpPath` setting to filter more specifically than by host alone when pulling credentials.
In my case, I have several credentials for `[username]@gitlab.com` depending on what path is being contributed to.
> Update git credential helper script to support path filtering
